### ISSUE TITLE
Info altro progetto 

### ISSUE THREAD

**Issue by Alex87a** [barbax7/edisubot#1]
Ciao Andrea, scusa il disturbo. Ho visto qualche tuo vecchio messaggio nel gruppo Telegram del progetto di sergioteula/python-amazon-paapi. Aprendo il tuo profilo, mi è saltato all'occhio il tuo canale, offerteKindle. Non sono qui per richieste di collaborazione, ma solamente per chiederti se fosse possibile sapere che bot utilizzi per creare i post con quello specifico formato e cosa per fare scraping dei prodotti su Amazon. Spero di non risultare troppo invadente e fuori luogo, ma non volevo disturbarti in chat privata su Telegram stesso.
Anticipatamente ti ringrazio.

**Comment by barbax7** [comment]
Visto che hai il mio contatto, scrivimi. Questo non è il posto adatto per parlarne, essendo relativo a uno specifico progetto.
